import turtle

T = turtle.Turtle()
T.speed(7)
T.pensize(5)
T.pencolor("red")

while True:
    T.penup()
    T.goto(-50,-100)
    T.pendown()
    T.circle(100)
    T.clear()
    T.penup()
    T.goto(0,-100)
    T.pendown()
    T.circle(100)
    T.clear()
    T.penup()
    T.goto(50,-100)
    T.pendown()
    T.circle(100)
    T.clear()
    T.penup()
    T.goto(100,-100)
    T.pendown()
    T.circle(100)
    T.clear()
    T.penup()
    T.goto(-100,-100)
    T.pendown()
    T.circle(100)
    T.clear()
